### ISSUE TITLE
Normalize the README with other Atom-IDE packages

### ISSUE THREAD

**Issue by ghisvail** [josa42/atom-ide-docker#4]
Have a look at [ide-typescript] for a good example. The structure is basically a one line summary of which service is supporting the language server, a snapshot of the plugin in action, an early access disclaimer, a list of features currently supported and the usual contributing and license sections.

Most Atom-IDE packages follow this outline, and it would be nice if this plugin would conform to it too.

**Comment by rcjsuen** [comment]
Why was this closed? The README.md still seems quite lacking compared to what's in the [atom/ide-typescript](atom/ide-typescript) repository.
