### ISSUE TITLE
Many commands deserve more flavor in the outline

### ISSUE THREAD

**Issue by kwerle** [josa42/atom-ide-docker#5]
Just having 'ENV' in the outline is pretty thin.
`ENV MY_VARIABLE_NAME`
would be MUCH more interesting.

**Comment by josa42** [comment]
Actually, this plugin just uses the information provided by the language server ([`rcjsuen/dockerfile-language-server-nodejs`](https://github.com/rcjsuen/dockerfile-language-server-nodejs)), so might want to open an issue there.
